2.3.2 - more prep for the factory, update for build-boto-services
See release-notes.md

diff --git a/cpan-dist/Makefile b/cpan-dist/Makefile
--- a/cpan-dist/Makefile
+++ b/cpan-dist/Makefile
@@ -1,10 +1,15 @@
 # -*- mode: makefile-gmake; -*-
 # make SERVICE=service-name
+SHELL := /bin/bash
+
+.SHELLFLAGS := -ec
 
 CPAN_DIST_MAKER=make-cpan-dist.pl
 
+NO_ECHO ?= @
+
 cpan: buildspec.yml api
-	@service=$$(cat service); \
+	$(NO_ECHO)service=$$(cat service); \
 	module_name=$$(cat module); \
 	test -n "$$DEBUG" && set -x; \
 	test -n "$$DEBUG" && DEBUG="--debug"; \
@@ -25,11 +30,10 @@ cpan: buildspec.yml api
 	$(MAKE) clean
 
 api: $(BOTOCORE)
-	@if ! test -d "./lib"; then \
+	$(NO_ECHO)if ! test -d "./lib"; then \
 	  mkdir lib; \
-	fi
-
-	@boto_service=$$(cat service); \
+	fi; \
+	boto_service=$$(cat service); \
 	module_name=$$(cat module); \
 	if test -n "$$TIDY"; then \
 	  TIDY="--tidy"; \
@@ -38,7 +42,13 @@ api: $(BOTOCORE)
 	for a in stub shapes; do \
 	  echo "creating...$$a"; \
 	  amazon-api $$TIDY -b $$(pwd) -s $$boto_service -m $$module_name -o lib create-$$a; \
-	done
+	done; \
+	module_path=$$(echo "lib/Amazon/API/$${module_name}.pm" | sed -e 's/::/\//g;'); \
+	service_date=$$(build-boto-services -p botocore list $$boto_service | jq -r .date); \
+        service_date="$${service_date//-/.}"; \
+	echo $$service_date; \
+	sed -e 's/[@]SERVICE_VERSION[@]/'$$service_date'/' $$module_path > $${module_path}.tmp; \
+	mv $${module_path}.tmp $${module_path}; \
 	for a in $$(find lib -name '*.pm'); do \
 	  temp="$${a%.pm}"; \
 	  podextract -i $$a -o $$a.tmp -p "$${temp}.pod"; \
@@ -70,24 +80,25 @@ query.services:
 	grep -ri '"protocol":' $(BOTOCORE_BASE) | grep 'query' | \
 	  cut -f 4 -d '/' | sort -u > $@
 
-service: service-listing.json
-	@if test -n "$(SERVICE)"; then \
+service:
+	$(NO_ECHO)if [[ -n "$(SERVICE)" ]]; then \
 	  echo "$(SERVICE)" | tr [A-Z] [a-z] > $@; \
-	elif test -n "$(MODULE_NAME)"; then \
+	elif [[ -n "$(MODULE_NAME)" ]]; then \
 	  echo "$(MODULE_NAME)" | tr [A-Z] [a-z] > $@; \
 	else \
 	  echo "ERROR: usage: make MODULE_NAME=module or SERVICE=service"; \
 	  false; \
 	fi
 	service=$$(cat $@); \
-	if test -z $$(find botocore/botocore/data -type d -name $$service 2>/dev/null); then \
-	  >&2 echo "ERROR: no such service $$service"; \
-	  rm -f $@ module; \
-	  false; \
+	service_found="$$(find botocore/botocore/data -mindepth 1 -maxdepth 1 -type d -name $$service 2>/dev/null)"; \
+	if [[ -z "$$service_found" ]]; then \
+	  echo >&2 "ERROR: no such service $$service"; \
+	  rm -f $@ module && exit 1; \
 	fi
 
 define script
 require Text::ASCIITable;
+use JSON;
 
 my $s = <>;
 
@@ -107,56 +118,63 @@ endef
 export scriptlet = $(value script)
 
 list-services: service-listing.json
-	@if perl -MText::ASCIITable -e 1 2>/dev/null; then \
-	  perl -MText::ASCIITable -MJSON -0 -e "$$scriptlet" $<; \
+	$(NO_ECHO)if perl -MText::ASCIITable -e 1 2>/dev/null; then \
+	  perl -0 -e "$$scriptlet" $<; \
 	else \
 	  jq --sort-keys . service-listing.json; \
 	fi
 
 service-listing.json: botocore
-	@JQ=$$(command -v jq); \
+	$(NO_ECHO)JQ=$$(command -v jq); \
 	if test -z "$$JQ"; then \
 	 >&2 echo "ERROR: no jq found...install jq"; \
 	 false; \
 	fi; \
 	listing=$$(mktemp); \
-	for a in $$(find botocore/botocore/data -maxdepth 1 -type d); do \
-	  if [ "$$(basename $$a)" != "data" ]; then \
-	    echo "$$(basename $$a),$$($$JQ -r .metadata.serviceFullName $$a/$$(ls -1 $$a | sort | tail -1)/service*)" >>$$listing; \
-	  fi; \
+	for a in $$(find botocore/botocore/data -mindepth 1 -maxdepth 1 -type d); do \
+	  echo "$$(basename $$a),$$($$JQ -r .metadata.serviceFullName $$a/$$(ls -1 $$a | sort | tail -1)/service*)" >>$$listing; \
 	done; \
-	perl -MJSON -e 'while(<>) { chomp; ($$k,$$v) = split /,/,$$_; $$listing{$$k} = $$v; }; print JSON->new->pretty->encode(\%listing);' $$listing >$@; \
+	perl -MJSON::XS -e 'while(<>) { chomp; ($$k,$$v) = split /,/,$$_; $$listing{$$k} = $$v; }; print JSON::XS->new->pretty->encode(\%listing);' $$listing >$@; \
 	rm $$listing;
 
 module: service
-	@if test -z "$(MODULE_NAME)"; then \
+	$(NO_ECHO)if test -z "$(MODULE_NAME)"; then \
 	  echo "$(SERVICE)" | tr [a-z] [A-Z] > $@; \
 	else \
 	  echo "$(MODULE_NAME)" > $@; \
 	fi
 
 buildspec.yml: buildspec.yml.in service module
-	@service=$$(cat service); \
+	$(NO_ECHO)service=$$(cat service); \
+	GIT=$$(command -v git || true); \
 	module_name=$$(cat module); \
-	if test -z "$$service" && test -z "$$module_name"; then \
+	if [[ -z "$$service" ]] && [[ -z "$$module_name" ]]; then \
 	  echo "no SERVICE or MODULE_NAME specified - make SERVICE=ecr"; \
 	  false; \
 	fi; \
-	if test -z "$$EMAIL"; then \
-	  EMAIL=$$(git config --global --get user.email); \
+	if [[ -z "$$EMAIL" ]]; then \
+	  if [[ -n "$$GIT" ]]; then \
+	    EMAIL=$$($$GIT config --global --get user.email); \
+	  else \
+	    EMAIL="rclauer@gmail.com"; \
+	  fi; \
 	fi; \
-	if test -z "$$FULLNAME"; then \
-	  FULLNAME=$$(git config --global --get user.name); \
+	if [[ -z "$$FULLNAME" ]]; then \
+	  if [[ -n "$$GIT" ]]; then \
+	    FULLNAME=$$($$GIT config --global --get user.name); \
+	  else \
+	    FULLNAME='aws-api-autobuilder'; \
+	  fi; \
 	fi; \
 	DATE=$$(date +%Y-%m-%d); \
 	sed \
 	-e "s/@date@/$$DATE/g" \
 	-e "s/@service@/$$module_name/g" \
 	-e "s/@email@/$$EMAIL/g" \
-	-e "s/@name@/$$FULLNAME/g" $< > $@
+	-e "s/@name@/$$FULLNAME/g" $< > $@ || true
 
 botocore:
-	@if test -n "$$BOTOCORE_PATH" && grep -q 'botocore.git' "$$BOTOCORE_PATH/.git/config"; then \
+	$(NO_ECHO)if test -n "$$BOTOCORE_PATH" && grep -q 'botocore.git' "$$BOTOCORE_PATH/.git/config"; then \
 	  ln -sf $$BOTOCORE_PATH botocore; \
 	else \
 	   git clone https://github.com/boto/botocore.git/; \
@@ -174,5 +192,5 @@ CLEANFILES = \
     module
 
 clean:
-	@rm -rf lib/
-	@rm -f $(CLEANFILES)
+	$(NO_ECHO)rm -rf lib/
+	$(NO_ECHO)rm -f $(CLEANFILES)
